import type { Metadata } from "next";
import "./globals.css";
import React, { ReactNode } from "react";
import Layout from "@/components/layout";

export const metadata: Metadata = {
	title: "YL store",
	description: "Generated by YL store",
};

interface RootLayoutProps {
	children: ReactNode;
	params: { locale: string };
}

export default function RootLayout({
	children,
	params: { locale },
}: RootLayoutProps) {
	return (
		<html lang={locale}>
			<body>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
