import type { Metadata } from "next";
import "./globals.css";
import React, { ReactNode } from "react";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "YL store",
	description: "Generated by YL store",
};

interface RootLayoutProps {
	children: ReactNode;
	params: { locale: string };
}

export default async function RootLayout({
	children,
	params: { locale },
}: RootLayoutProps) {
	return (
		<html lang={locale}>
			<body>
				<Nav lng={locale} />
				{children}
				<Footer />
			</body>
		</html>
	);
}
